### ISSUE TITLE
Process feedback JOSS

### ISSUE THREAD

**Issue by richelbilderbeek** [ropensci/mcbette#37]
My JOSS submission can be found at [https://github.com/openjournals/joss-reviews/issues/2738](https://github.com/openjournals/joss-reviews/issues/2738).

Process the first feedback:

> open source license

Upon your request, I have added the LICENSE file.

> DOI's are missing from references (see list above)

Fixed the DOIs indited by [this](https://github.com/openjournals/joss-reviews/issues/2738#issuecomment-706222339) @whelan commit.

> Your paper needs a high level non-technical short introduction to orient a reader who might be interested in using your software to decide whether it is relevant or not.

AFAICS the Introduction serves that purpose:

>``mcbette`` is an R package to do model comparison between
a set of evolutionary models on a DNA alignment, which allows
to select that model that is closest to the process that underlied
the DNA alignment and species tree.

I assume the rOpenSci reviewers agree. If you disagree, let me know and I will make it less technical :+1:

> you should be able to resize your giant logo in the paper too

Done!

**Comment by kthyng** [comment]
> 
> The package does have an open source license, which is GPL-3, as can be seen [in this line in the DESCRIPTION file](https://github.com/ropensci/mcbette/blob/master/DESCRIPTION#L31)

You need an actual LICENSE file that contains the license language, instead of the name of an open source license listed as is presently.

> 
> > Your paper needs a high level non-technical short introduction to orient a reader who might be interested in using your software to decide whether it is relevant or not.
> 
> I assume the rOpenSci review [here](https://github.com/ropensci/software-review/issues/360) is sufficient?
> 

I'm not sure what part of that review you are referring to. I mean you should add a few sentences to the start of your JOSS paper that describe your software at a high level. If you have already written some description that would work, that is fine to use.

**Comment by richelbilderbeek** [comment]
Done, processed the feedback and posted the reply at the original post at [https://github.com/openjournals/joss-reviews/issues/2738](https://github.com/openjournals/joss-reviews/issues/2738)
