### ISSUE TITLE
Error: dir.exists(examples_folder) is not TRUE on Windows: mcbette does not work under Windows

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/mcbette#39]
**Describe the bug**
A reader of your [blog post commented](https://discuss.ropensci.org/t/ropensci-selecting-the-best-phylogenetic-evolutionary-model/2271/3) "it says Error: dir.exists(examples_folder) is not TRUE, on mac can you please help, thanks" https://discuss.ropensci.org/t/ropensci-selecting-the-best-phylogenetic-evolutionary-model/2271/3

I asked them to open a bug report issue, but figured you would want to know.

**Comment by richelbilderbeek** [comment]
@stefaniebutland thanks so much! 

I'll keep this Issue open until the user has responded for my reference :rainbow:

**Comment by richelbilderbeek** [comment]
Note to self:

```
mcbette bug report

5 December 2020 15:25 3 KB
From: Richel Bilderbeek
To: [dksamuel]

Hi Dr. Samuel,

I contact you as you have posted a possible mcbette error at the mcbette blog [1]. As a blog post comment is not the best place to submit a bug report, Stefanie Butland redirected you to the mcbette code repository. From there on, there has been no response from your side, hence I contact you.

Has the problem already been resolved?

 * If yes: great!
 * If no: please submit a bug report at the mcbette repository by creating a new Issue, using the 'Bug report' template

Thanks and cheers, Richel Bilderbeek


 * [1] https://discuss.ropensci.org/t/ropensci-selecting-the-best-phylogenetic-evolutionary-model/2271/3
 * [2] https://github.com/ropensci/mcbette/issues/39
```

**Comment by richelbilderbeek** [comment]
Re: mcbette bug report

5 December 2020 16:32 7 KB
From:
Duleep Samuel
To:
[richel]

Sir, thanks, on reading I found that mcbette works only on Mac or Linux. As I had earlier tried in win 10, I tried today  in the Mac. Mcbette installs nicely with all dependencies. It runs the examples well. But  this problem persists. I will submit a detailed bug report in the template on Monday. I wanted to be sure that my system setup was working before I submitted a bug report.Thanks a lot. Samuel Bangalore India

**Comment by richelbilderbeek** [comment]
Re: mcbette bug report: indeed does not work on Windows

5 December 2020 16:37 6 KB
From:
Richel Bilderbeek
To:
Duleep Samuel

Hi Dr Samuel,

> I found that mcbette works only on Mac or Linux.

That is completely correct and it is documented as such on https://github.com/ropensci/mcbette#installation . This has nothing to do with mcbette, yet due to that the BEAST2 packages cannot be called from a script on Windows.

Cheers, Richel

**Comment by richelbilderbeek** [comment]
@dksamuel, can I close this Issue?

If no response, I will close this Issue Dec 14th 2020.

**Comment by richelbilderbeek** [comment]
I have added this question to [the mcbette FAQ](https://github.com/ropensci/mcbette/#under-which-platforms-does-mcbette-work)

Thanks @dksamuel / @dksam for signalling that I should have done so sooner :+1:

**Comment by richelbilderbeek** [comment]
He answered by email: yes :+1:

Closing this Issue!
