### ISSUE TITLE
install.packages("mcbette") failed due to "ERROR: configuration failed for package ‘Rmpfr’".

### ISSUE THREAD

**Issue by cjwoodruff50** [ropensci/mcbette#40]
Failure apparently due to missing elements in C-code 
checking mpfr.h usability... no
checking mpfr.h presence... no
checking for mpfr.h... no

**Comment by richelbilderbeek** [comment]
Hi Chris,

Thanks for posting this Issue!

The reason for this installation error, is that you have not yet installed the mpfr library. The developers of Rmpfr even added a helpful message in the error you've just posted only part of. I only know the solution for Linux for the Ubuntu distro, as [can be seen in the Travis CI build script](https://github.com/ropensci/mcbette/blob/master/.travis.yml#L36):

```
sudo apt install libmpfr-dev
```

I hope that helps :+1:

**Comment by cjwoodruff50** [comment]
Richel,
                Thanks very much for your prompt and informative reply.  I’ll try to sort out my end of this tomorrow morning.  The package looks too good not to be given a real try out!
Chris

**Comment by richelbilderbeek** [comment]
@cjwoodruff50 happy to read your response. If you run into mcbette troubles, let me know!

Good luck installing Rmpfr :+1: 

Closing this Issue :rainbow:

**Comment by cjwoodruff50** [comment]
Richel,
                Mcbette working – but required Institute IT department to install mpfr as a user-loadable module on the Centos 7 system.  The standard install.p[ackages() call then worked perfectly.

                This may be useful information for you.
Chris

**Comment by richelbilderbeek** [comment]
@cjwoodruff50: happy to hear it works and thanks for the info!
